version: "2"
services:
  app:
    container_name: "music-smoker-app"
    image: "music-smoker-app"
    volumes:
      - .:/usr/src/app/
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - redis
    links:
      - "mongo:database"
  mongo:
    container_name: "mongodb"
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379