FROM node:latest

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY ./laboratorio5/package.json /usr/src/app

RUN npm install

COPY ./laboratorio5 /usr/src/app

EXPOSE 3001

CMD node index.js


#$ docker build -t music-smoker-app . 
